### ISSUE TITLE
Open preferences 

### ISSUE THREAD

**Issue by nikohansen** [yujitach/MenuMeters#185]
I was trying MenuMeters version 2.0.8.1 on a MacBook Pro 16-inch under Catalina 10.15.7. When I click on "Open MenuMeters preferences" nothing seems to happen. Also, I only see the disk usage icon in the Mac menu bar and nothing else. With version 2.0.7 all works fine.

**Comment by xaroth8088** [comment]
👍 Was just about to report the same, same OS.  Happens both with clean installs of 2.0.8 and 2.0.8.1, and when using the in-app update from 2.0.7 -> 2.0.8.1

**Comment by yujitach** [comment]
Thanks. I also got the same bug report via an email. 

But I can't so far reproduce the bug on my two Macs. This makes it very difficult for me to fix this issue...

**Comment by yujitach** [comment]
Is it that "Open MenuMeters Preferences" does not work from all MenuMeters? Or does it work from some MenuMeter and not from other MenuMeter?

In the meantime, could you download the old version
		https://github.com/yujitach/MenuMeters/releases/tag/2.0.7
and reinstall it? Does it work again then?

**Comment by yujitach** [comment]
I would also appreciate if you could create a new account on your Mac, install MenuMeters 2.0.8.1 there, and see if you encounter the same bug. On my Mac I didn't see any problem on a newly created account ...

**Comment by nikohansen** [comment]
> Is it that "Open MenuMeters Preferences" does not work from all MenuMeters? Or does it work from some MenuMeter and not from other MenuMeter?

I only see a single meter icon:

<img width="48" alt="Screen Shot 2020-10-31 at 20 04 44" src="https://user-images.githubusercontent.com/7316439/97816428-667b6600-1c95-11eb-9446-108ac1494fab.png">

**Comment by nikohansen** [comment]
After creating a new account it does work. In my case, the setup comes from a previous MacBook data transfer (and looks exactly as setup previously under 2.0.7). I believe it was still called `MenuMetersApp` rather than `MenuMeters`.

**Comment by yujitach** [comment]
Is it that you use "Automatically hide and show the menu bar" reported in #189 ? I can indeed reproduce what you described with this option on. Let me now try to debug it...

**Comment by yujitach** [comment]
Released the update https://github.com/yujitach/MenuMeters/releases/tag/2.0.8.2 which should solve this issue. Please tell me if it works or not.

**Comment by xaroth8088** [comment]
At first, the update from 2.0.7 to 2.0.8.2 had the same behavior as before.  After quitting MenuMeters (double-click the app, `cmd-Q`), deleting the app, and then installing 2.0.8.2 also had the same behavior.  I then disabled menu auto-hiding, and the same bug was present.

Then, I uninstalled 2.0.8.2 and re-installed 2.0.7.  From there, I checked the `Display CPU Meter` checkbox, quit the app, re-ran it, let it auto-update, and now it's working correctly - even after turning menu auto-hide on again.  I don't know what step in that process caused it to work again, but at least it's working.  🤷

**Comment by PikachuEXE** [comment]
I am actually able to open preferences no MacOS 10.15.7 (19H2) with MacBook Pro (15-inch, 2018)
with `2.0.8.1` but **not** `2.0.8.2`

**Comment by AussieFlem** [comment]
Still unable to open preferences in 2.0.8.2.
Works as expected in 2.0.7
Mac OS 10.15.7 (19H2) on a MacBook Pro 15" (2016)

**Comment by yujitach** [comment]
Sorry for the mess. I would appreciate if you could also report
- which MenuMeters are seen in the menu bar
- whether the menu bar is set to the auto-hide mode
- if so, whether it works if the auto-hide mode is disabled

**Comment by AussieFlem** [comment]
CPU (per CPU) and temperature.
Unsure about auto-hide (can't open preferences to check) but App doesn't show in the switcher - seems to be working as expected other than being unable to open the preferences.

**Comment by yujitach** [comment]
@PikachuEXE  @AussieFlem  How about https://github.com/yujitach/MenuMeters/releases/tag/2.0.8.3 ?

**Comment by AussieFlem** [comment]
Yep, that looks good. Installed the update from in-app from 2.0.7 and it popped the preferences straight away on completion.

**Comment by PikachuEXE** [comment]
`2.0.8.3`
Can open preference panel

**Comment by yujitach** [comment]
@AussieFlem @PikachuEXE Thanks, I'm relieved.
